psb:
  hotel:
    api:
      base-url: http://58.210.180.134:8891/HotelSer
      connect-timeout: 5000
      read-timeout: 5000

jwt:
  secret: ${JWT_SECRET:your-secret-key-must-be-at-least-32-bytes-long} # 建议在生产环境中使用环境变量
  token-validity: 2592000 # 30天，单位：秒
  token-prefix: "Bearer "
  header-name: "Authorization"
